name: dindin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.6
  get_it: ^7.6.0
  uuid: ^4.2.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  fluttertoast: ^8.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/app/images/brand/

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app/images/brand/logo_icon.png"
  remove_alpha_ios: true
