import 'package:dindin/src/core/styles/colors.dart';
import 'package:flutter/material.dart';

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: primaryColor,
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFC6ECFF),
  onPrimaryContainer: Color(0xFF04283B),
  secondary: Color(0xFF04283B),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFC6ECFF),
  onSecondaryContainer: Color(0xFF042739),
  tertiary: Color(0xFFC6ECFF),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFC6ECFF),
  onTertiaryContainer: Color(0xFF042739),
  error: Color(0xFFB3261E),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFF9DEDC),
  onErrorContainer: Color(0xFF410E0B),
  outline: Color(0xFF79747E),
  surface: Color(0xFFFBFBFB),
  onSurface: Color(0xFF1D1B20),
  onSurfaceVariant: Color(0xFF49454F),
  inverseSurface: Color(0xFF322F35),
  onInverseSurface: Color(0xFFF5EFF7),
  inversePrimary: Color(0xFFF4B1A4),
  shadow: Color(0xFF000000),
  outlineVariant: Color(0xFFF1EDF5),
  scrim: Color(0xFF000000),
  background: Colors.black,
  onBackground: Colors.white,
);

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: secondaryColor,
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFC6ECFF),
  onPrimaryContainer: Color(0xFF04283B),
  secondary: Color(0xFF04283B),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0XFFC6ECFF),
  onSecondaryContainer: Color(0xFF042739),
  tertiary: Color(0xFFC6ECFF),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFC6ECFF),
  onTertiaryContainer: Color(0xFF042739),
  error: Color(0xFFB3261E),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFF9DEDC),
  onErrorContainer: Color(0xFF410E0B),
  outline: Color(0XFF79747E),
  surface: Color(0xFFFBFBFB),
  onSurface: Color(0xFF1D1B20),
  onSurfaceVariant: Color(0xFF49454F),
  inverseSurface: Color(0xFF322F35),
  onInverseSurface: Color(0xFFF5EFF7),
  inversePrimary: Color(0xFFF4B1A4),
  shadow: Color(0xFF000000),
  outlineVariant: Color(0xFFF1EDF5),
  scrim: Color(0xFF000000),
  background: Colors.white,
  onBackground: Colors.black,
);
